CREATE DATABASE Hotel;

-- Usar la base de datos Hotel
USE Hotel;

CREATE TABLE IF NOT EXISTS Cliente (
    ID_Cliente INT AUTO_INCREMENT PRIMARY KEY,
    Nombre_Cliente VARCHAR(100),
    Apellido_Cliente VARCHAR(100),
    Teléfono_Cliente VARCHAR(15),
    Email VARCHAR(100),
    País VARCHAR(100),
    Huespe INT,
    RRHH TINYINT(1) DEFAULT 0 -- Columna adicional para indicar si el cliente pertenece al departamento de RRHH
);

CREATE TABLE IF NOT EXISTS Empleado (
    ID_Empleado INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    Apellido VARCHAR(100),
    Cargo VARCHAR(100),
    Dirección VARCHAR(255),
    RRHH BOOLEAN
);

-- Crear la tabla Reserva
CREATE TABLE IF NOT EXISTS Reserva (
    ID_Reserva INT AUTO_INCREMENT PRIMARY KEY,
    ID_Cliente INT,
    Checkin DATETIME,
    Checkout DATETIME,
    Numero_Habitaciones INT,
    FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente)
);

-- Crear la tabla Habitación si no existe y agregar columnas
CREATE TABLE IF NOT EXISTS Habitación (
    ID_Habitación INT AUTO_INCREMENT PRIMARY KEY,
    Tipo VARCHAR(100),
    Precio DECIMAL(10, 2),
    Disponible BOOLEAN,
    RRHH BOOLEAN DEFAULT FALSE -- Columna adicional para indicar si la habitación es para RRHH
);

-- Crear la tabla Tipo de Habitación
CREATE TABLE IF NOT EXISTS Tipo_Habitación (
    ID_Tipo INT AUTO_INCREMENT PRIMARY KEY,
    Tipo VARCHAR(100),
    Descripción VARCHAR(200)
);

-- Crear la tabla Paquete
CREATE TABLE IF NOT EXISTS Paquete (
    ID_Paquete INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    Descripción VARCHAR(200),
    Precio DECIMAL(10, 2)
);

-- Crear la tabla Extras
CREATE TABLE IF NOT EXISTS Extras (
    ID_Extra INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100),
    Precio DECIMAL(10, 2)
);

-- Crear la tabla Método de Pago
CREATE TABLE IF NOT EXISTS Metodo_Pago (
    ID_Metodo INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100)
);

-- Crear la tabla Facturación
CREATE TABLE IF NOT EXISTS Facturación (
    ID_Factura INT AUTO_INCREMENT PRIMARY KEY,
    ID_Habitación INT,
    ID_Paquete INT,
    ID_Extra INT,
    ID_Metodo_Pago INT,
    Fecha DATE,
    Precio DECIMAL(10, 2),
    FOREIGN KEY (ID_Habitación) REFERENCES Habitación(ID_Habitación),
    FOREIGN KEY (ID_Paquete) REFERENCES Paquete(ID_Paquete),
    FOREIGN KEY (ID_Extra) REFERENCES Extras(ID_Extra),
    FOREIGN KEY (ID_Metodo_Pago) REFERENCES Metodo_Pago(ID_Metodo)
);

-- Crear la tabla Dirección
CREATE TABLE IF NOT EXISTS Dirección (
    ID_Direccion INT AUTO_INCREMENT PRIMARY KEY,
    Pais VARCHAR(100),
    Estado VARCHAR(100),
    Ciudad VARCHAR(100),
    Dirección VARCHAR(255)
);

-- Insertar datos en la tabla Dirección
INSERT INTO Dirección (Pais, Estado, Ciudad, Dirección)
VALUES 
('Afganistán', 'Estado_Afganistán', 'Ciudad_Afganistán', 'Dirección_Afganistán'),
('Albania', 'Estado_Albania', 'Ciudad_Albania', 'Dirección_Albania'),
('Alemania', 'Estado_Alemania', 'Ciudad_Alemania', 'Dirección_Alemania'),
('Andorra', 'Estado_Andorra', 'Ciudad_Andorra', 'Dirección_Andorra'),
('Angola', 'Estado_Angola', 'Ciudad_Angola', 'Dirección_Angola'),
('Antigua y Barbuda', 'Estado_Antigua y Barbuda', 'Ciudad_Antigua y Barbuda', 'Dirección_Antigua y Barbuda'),
('Arabia Saudita', 'Estado_Arabia Saudita', 'Ciudad_Arabia Saudita', 'Dirección_Arabia Saudita'),
('Argelia', 'Estado_Argelia', 'Ciudad_Argelia', 'Dirección_Argelia'),
('Argentina', 'Estado_Argentina', 'Ciudad_Argentina', 'Dirección_Argentina'),
('Armenia', 'Estado_Armenia', 'Ciudad_Armenia', 'Dirección_Armenia'),
('Australia', 'Estado_Australia', 'Ciudad_Australia', 'Dirección_Australia'),
('Austria', 'Estado_Austria', 'Ciudad_Austria', 'Dirección_Austria'),
('Azerbaiyán', 'Estado_Azerbaiyán', 'Ciudad_Azerbaiyán', 'Dirección_Azerbaiyán'),
('Bahamas', 'Estado_Bahamas', 'Ciudad_Bahamas', 'Dirección_Bahamas'),
('Bahrein', 'Estado_Bahrein', 'Ciudad_Bahrein', 'Dirección_Bahrein'),
('Bangladés', 'Estado_Bangladés', 'Ciudad_Bangladés', 'Dirección_Bangladés'),
('Barbados', 'Estado_Barbados', 'Ciudad_Barbados', 'Dirección_Barbados'),
('Bélgica', 'Estado_Bélgica', 'Ciudad_Bélgica', 'Dirección_Bélgica'),
('Belice', 'Estado_Belice', 'Ciudad_Belice', 'Dirección_Belice'),
('Benín', 'Estado_Benín', 'Ciudad_Benín', 'Dirección_Benín'),
('Bielorrusia', 'Estado_Bielorrusia', 'Ciudad_Bielorrusia', 'Dirección_Bielorrusia'),
('Bolivia', 'Estado_Bolivia', 'Ciudad_Bolivia', 'Dirección_Bolivia'),
('Bosnia y Herzegovina', 'Estado_Bosnia y Herzegovina', 'Ciudad_Bosnia y Herzegovina', 'Dirección_Bosnia y Herzegovina'),
('Botsuana', 'Estado_Botsuana', 'Ciudad_Botsuana', 'Dirección_Botsuana'),
('Brasil', 'Estado_Brasil', 'Ciudad_Brasil', 'Dirección_Brasil'),
('Brunei', 'Estado_Brunei', 'Ciudad_Brunei', 'Dirección_Brunei'),
('Bulgaria', 'Estado_Bulgaria', 'Ciudad_Bulgaria', 'Dirección_Bulgaria'),
('Burkina Faso', 'Estado_Burkina Faso', 'Ciudad_Burkina Faso', 'Dirección_Burkina Faso'),
('Burundi', 'Estado_Burundi', 'Ciudad_Burundi', 'Dirección_Burundi'),
('Bután', 'Estado_Bután', 'Ciudad_Bután', 'Dirección_Bután'),
('Cabo Verde', 'Estado_Cabo Verde', 'Ciudad_Cabo Verde', 'Dirección_Cabo Verde'),
('Camboya', 'Estado_Camboya', 'Ciudad_Camboya', 'Dirección_Camboya'),
('Camerún', 'Estado_Camerún', 'Ciudad_Camerún', 'Dirección_Camerún'),
('Canadá', 'Estado_Canadá', 'Ciudad_Canadá', 'Dirección_Canadá'),
('Catar', 'Estado_Catar', 'Ciudad_Catar', 'Dirección_Catar'),
('Chad', 'Estado_Chad', 'Ciudad_Chad', 'Dirección_Chad'),
('Chequia', 'Estado_Chequia', 'Ciudad_Chequia', 'Dirección_Chequia'),
('Chile', 'Estado_Chile', 'Ciudad_Chile', 'Dirección_Chile'),
('China', 'Estado_China', 'Ciudad_China', 'Dirección_China'),
('Chipre', 'Estado_Chipre', 'Ciudad_Chipre', 'Dirección_Chipre'),
('Colombia', 'Estado_Colombia', 'Ciudad_Colombia', 'Dirección_Colombia'),
('Comoras', 'Estado_Comoras', 'Ciudad_Comoras', 'Dirección_Comoras'),
('Corea del Norte', 'Estado_Corea del Norte', 'Ciudad_Corea del Norte', 'Dirección_Corea del Norte'),
('Corea del Sur', 'Estado_Corea del Sur', 'Ciudad_Corea del Sur', 'Dirección_Corea del Sur'),
('Costa de Marfil', 'Estado_Costa de Marfil', 'Ciudad_Costa de Marfil', 'Dirección_Costa de Marfil'),
('Costa Rica', 'Estado_Costa Rica', 'Ciudad_Costa Rica', 'Dirección_Costa Rica'),
('Croacia', 'Estado_Croacia', 'Ciudad_Croacia', 'Dirección_Croacia'),
('Cuba', 'Estado_Cuba', 'Ciudad_Cuba', 'Dirección_Cuba'),
('Dinamarca', 'Estado_Dinamarca', 'Ciudad_Dinamarca', 'Dirección_Dinamarca'),
('Dominica', 'Estado_Dominica', 'Ciudad_Dominica', 'Dirección_Dominica'),
('Ecuador', 'Estado_Ecuador', 'Ciudad_Ecuador', 'Dirección_Ecuador'),
('Egipto', 'Estado_Egipto', 'Ciudad_Egipto', 'Dirección_Egipto'),
('El Salvador', 'Estado_El Salvador', 'Ciudad_El Salvador', 'Dirección_El Salvador'),
('Emiratos Árabes Unidos', 'Estado_Emiratos Árabes Unidos', 'Ciudad_Emiratos Árabes Unidos', 'Dirección_Emiratos Árabes Unidos'),
('Eritrea', 'Estado_Eritrea', 'Ciudad_Eritrea', 'Dirección_Eritrea'),
('Eslovaquia', 'Estado_Eslovaquia', 'Ciudad_Eslovaquia', 'Dirección_Eslovaquia'),
('Eslovenia', 'Estado_Eslovenia', 'Ciudad_Eslovenia', 'Dirección_Eslovenia'),
('España', 'Estado_España', 'Ciudad_España', 'Dirección_España'),
('Estados Unidos', 'Estado_Estados Unidos', 'Ciudad_Estados Unidos', 'Dirección_Estados Unidos'),
('Estonia', 'Estado_Estonia', 'Ciudad_Estonia', 'Dirección_Estonia'),
('Eswatini', 'Estado_Eswatini', 'Ciudad_Eswatini', 'Dirección_Eswatini'),
('Etiopía', 'Estado_Etiopía', 'Ciudad_Etiopía', 'Dirección_Etiopía'),
('Filipinas', 'Estado_Filipinas', 'Ciudad_Filipinas', 'Dirección_Filipinas'),
('Finlandia', 'Estado_Finlandia', 'Ciudad_Finlandia', 'Dirección_Finlandia'),
('Fiyi', 'Estado_Fiyi', 'Ciudad_Fiyi', 'Dirección_Fiyi'),
('Francia', 'Estado_Francia', 'Ciudad_Francia', 'Dirección_Francia'),
('Gabón', 'Estado_Gabón', 'Ciudad_Gabón', 'Dirección_Gabón'),
('Gambia', 'Estado_Gambia', 'Ciudad_Gambia', 'Dirección_Gambia'),
('Georgia', 'Estado_Georgia', 'Ciudad_Georgia', 'Dirección_Georgia'),
('Ghana', 'Estado_Ghana', 'Ciudad_Ghana', 'Dirección_Ghana'),
('Granada', 'Estado_Granada', 'Ciudad_Granada', 'Dirección_Granada'),
('Grecia', 'Estado_Grecia', 'Ciudad_Grecia', 'Dirección_Grecia'),
('Guatemala', 'Estado_Guatemala', 'Ciudad_Guatemala', 'Dirección_Guatemala'),
('Guinea', 'Estado_Guinea', 'Ciudad_Guinea', 'Dirección_Guinea'),
('Guinea-Bisáu', 'Estado_Guinea-Bisáu', 'Ciudad_Guinea-Bisáu', 'Dirección_Guinea-Bisáu'),
('Guinea Ecuatorial', 'Estado_Guinea Ecuatorial', 'Ciudad_Guinea Ecuatorial', 'Dirección_Guinea Ecuatorial'),
('Guyana', 'Estado_Guyana', 'Ciudad_Guyana', 'Dirección_Guyana'),
('Haití', 'Estado_Haití', 'Ciudad_Haití', 'Dirección_Haití'),
('Honduras', 'Estado_Honduras', 'Ciudad_Honduras', 'Dirección_Honduras'),
('Hungría', 'Estado_Hungría', 'Ciudad_Hungría', 'Dirección_Hungría'),
('India', 'Estado_India', 'Ciudad_India', 'Dirección_India'),
('Indonesia', 'Estado_Indonesia', 'Ciudad_Indonesia', 'Dirección_Indonesia'),
('Irak', 'Estado_Irak', 'Ciudad_Irak', 'Dirección_Irak'),
('Irán', 'Estado_Irán', 'Ciudad_Irán', 'Dirección_Irán'),
('Irlanda', 'Estado_Irlanda', 'Ciudad_Irlanda', 'Dirección_Irlanda'),
('Islandia', 'Estado_Islandia', 'Ciudad_Islandia', 'Dirección_Islandia'),
('Islas Marshall', 'Estado_Islas Marshall', 'Ciudad_Islas Marshall', 'Dirección_Islas Marshall'),
('Islas Salomón', 'Estado_Islas Salomón', 'Ciudad_Islas Salomón', 'Dirección_Islas Salomón'),
('Israel', 'Estado_Israel', 'Ciudad_Israel', 'Dirección_Israel'),
('Italia', 'Estado_Italia', 'Ciudad_Italia', 'Dirección_Italia'),
('Jamaica', 'Estado_Jamaica', 'Ciudad_Jamaica', 'Dirección_Jamaica'),
('Japón', 'Estado_Japón', 'Ciudad_Japón', 'Dirección_Japón'),
('Jordania', 'Estado_Jordania', 'Ciudad_Jordania', 'Dirección_Jordania'),
('Kazajistán', 'Estado_Kazajistán', 'Ciudad_Kazajistán', 'Dirección_Kazajistán'),
('Kenia', 'Estado_Kenia', 'Ciudad_Kenia', 'Dirección_Kenia'),
('Kirguistán', 'Estado_Kirguistán', 'Ciudad_Kirguistán', 'Dirección_Kirguistán'),
('Kiribati', 'Estado_Kiribati', 'Ciudad_Kiribati', 'Dirección_Kiribati'),
('Kosovo', 'Estado_Kosovo', 'Ciudad_Kosovo', 'Dirección_Kosovo'),
('Kuwait', 'Estado_Kuwait', 'Ciudad_Kuwait', 'Dirección_Kuwait'),
('Laos', 'Estado_Laos', 'Ciudad_Laos', 'Dirección_Laos'),
('Lesoto', 'Estado_Lesoto', 'Ciudad_Lesoto', 'Dirección_Lesoto'),
('Letonia', 'Estado_Letonia', 'Ciudad_Letonia', 'Dirección_Letonia'),
('Líbano', 'Estado_Líbano', 'Ciudad_Líbano', 'Dirección_Líbano'),
('Liberia', 'Estado_Liberia', 'Ciudad_Liberia', 'Dirección_Liberia'),
('Libia', 'Estado_Libia', 'Ciudad_Libia', 'Dirección_Libia'),
('Liechtenstein', 'Estado_Liechtenstein', 'Ciudad_Liechtenstein', 'Dirección_Liechtenstein'),
('Lituania', 'Estado_Lituania', 'Ciudad_Lituania', 'Dirección_Lituania'),
('Luxemburgo', 'Estado_Luxemburgo', 'Ciudad_Luxemburgo', 'Dirección_Luxemburgo'),
('Macedonia del Norte', 'Estado_Macedonia del Norte', 'Ciudad_Macedonia del Norte', 'Dirección_Macedonia del Norte'),
('Madagascar', 'Estado_Madagascar', 'Ciudad_Madagascar', 'Dirección_Madagascar'),
('Malasia', 'Estado_Malasia', 'Ciudad_Malasia', 'Dirección_Malasia'),
('Malaui', 'Estado_Malaui', 'Ciudad_Malaui', 'Dirección_Malaui'),
('Maldivas', 'Estado_Maldivas', 'Ciudad_Maldivas', 'Dirección_Maldivas'),
('Malí', 'Estado_Malí', 'Ciudad_Malí', 'Dirección_Malí'),
('Malta', 'Estado_Malta', 'Ciudad_Malta', 'Dirección_Malta'),
('Marruecos', 'Estado_Marruecos', 'Ciudad_Marruecos', 'Dirección_Marruecos'),
('Mauricio', 'Estado_Mauricio', 'Ciudad_Mauricio', 'Dirección_Mauricio'),
('Mauritania', 'Estado_Mauritania', 'Ciudad_Mauritania', 'Dirección_Mauritania'),
('México', 'Estado_México', 'Ciudad_México', 'Dirección_México'),
('Micronesia', 'Estado_Micronesia', 'Ciudad_Micronesia', 'Dirección_Micronesia'),
('Moldavia', 'Estado_Moldavia', 'Ciudad_Moldavia', 'Dirección_Moldavia'),
('Mónaco', 'Estado_Mónaco', 'Ciudad_Mónaco', 'Dirección_Mónaco'),
('Mongolia', 'Estado_Mongolia', 'Ciudad_Mongolia', 'Dirección_Mongolia'),
('Montenegro', 'Estado_Montenegro', 'Ciudad_Montenegro', 'Dirección_Montenegro'),
('Mozambique', 'Estado_Mozambique', 'Ciudad_Mozambique', 'Dirección_Mozambique'),
('Myanmar', 'Estado_Myanmar', 'Ciudad_Myanmar', 'Dirección_Myanmar'),
('Namibia', 'Estado_Namibia', 'Ciudad_Namibia', 'Dirección_Namibia'),
('Nauru', 'Estado_Nauru', 'Ciudad_Nauru', 'Dirección_Nauru'),
('Nepal', 'Estado_Nepal', 'Ciudad_Nepal', 'Dirección_Nepal'),
('Nicaragua', 'Estado_Nicaragua', 'Ciudad_Nicaragua', 'Dirección_Nicaragua'),
('Níger', 'Estado_Níger', 'Ciudad_Níger', 'Dirección_Níger'),
('Nigeria', 'Estado_Nigeria', 'Ciudad_Nigeria', 'Dirección_Nigeria'),
('Noruega', 'Estado_Noruega', 'Ciudad_Noruega', 'Dirección_Noruega'),
('Nueva Zelanda', 'Estado_Nueva Zelanda', 'Ciudad_Nueva Zelanda', 'Dirección_Nueva Zelanda'),
('Omán', 'Estado_Omán', 'Ciudad_Omán', 'Dirección_Omán'),
('Países Bajos', 'Estado_Países Bajos', 'Ciudad_Países Bajos', 'Dirección_Países Bajos'),
('Pakistán', 'Estado_Pakistán', 'Ciudad_Pakistán', 'Dirección_Pakistán'),
('Palaos', 'Estado_Palaos', 'Ciudad_Palaos', 'Dirección_Palaos'),
('Palestina', 'Estado_Palestina', 'Ciudad_Palestina', 'Dirección_Palestina'),
('Panamá', 'Estado_Panamá', 'Ciudad_Panamá', 'Dirección_Panamá'),
('Papúa Nueva Guinea', 'Estado_Papúa Nueva Guinea', 'Ciudad_Papúa Nueva Guinea', 'Dirección_Papúa Nueva Guinea'),
('Paraguay', 'Estado_Paraguay', 'Ciudad_Paraguay', 'Dirección_Paraguay'),
('Perú', 'Estado_Perú', 'Ciudad_Perú', 'Dirección_Perú'),
('Polonia', 'Estado_Polonia', 'Ciudad_Polonia', 'Dirección_Polonia'),
('Portugal', 'Estado_Portugal', 'Ciudad_Portugal', 'Dirección_Portugal'),
('Reino Unido', 'Estado_Reino Unido', 'Ciudad_Reino Unido', 'Dirección_Reino Unido'),
('República Centroafricana', 'Estado_República Centroafricana', 'Ciudad_República Centroafricana', 'Dirección_República Centroafricana'),
('República del Congo', 'Estado_República del Congo', 'Ciudad_República del Congo', 'Dirección_República del Congo'),
('República Democrática del Congo', 'Estado_República Democrática del Congo', 'Ciudad_República Democrática del Congo', 'Dirección_República Democrática del Congo'),
('República Dominicana', 'Estado_República Dominicana', 'Ciudad_República Dominicana', 'Dirección_República Dominicana'),
('Ruanda', 'Estado_Ruanda', 'Ciudad_Ruanda', 'Dirección_Ruanda'),
('Rumania', 'Estado_Rumania', 'Ciudad_Rumania', 'Dirección_Rumania'),
('Rusia', 'Estado_Rusia', 'Ciudad_Rusia', 'Dirección_Rusia'),
('Samoa', 'Estado_Samoa', 'Ciudad_Samoa', 'Dirección_Samoa'),
('San Cristóbal y Nieves', 'Estado_San Cristóbal y Nieves', 'Ciudad_San Cristóbal y Nieves', 'Dirección_San Cristóbal y Nieves'),
('San Marino', 'Estado_San Marino', 'Ciudad_San Marino', 'Dirección_San Marino'),
('San Vicente y las Granadinas', 'Estado_San Vicente y las Granadinas', 'Ciudad_San Vicente y las Granadinas', 'Dirección_San Vicente y las Granadinas'),
('Santa Lucía', 'Estado_Santa Lucía', 'Ciudad_Santa Lucía', 'Dirección_Santa Lucía'),
('Santo Tomé y Príncipe', 'Estado_Santo Tomé y Príncipe', 'Ciudad_Santo Tomé y Príncipe', 'Dirección_Santo Tomé y Príncipe'),
('Senegal', 'Estado_Senegal', 'Ciudad_Senegal', 'Dirección_Senegal'),
('Serbia', 'Estado_Serbia', 'Ciudad_Serbia', 'Dirección_Serbia'),
('Seychelles', 'Estado_Seychelles', 'Ciudad_Seychelles', 'Dirección_Seychelles'),
('Sierra Leona', 'Estado_Sierra Leona', 'Ciudad_Sierra Leona', 'Dirección_Sierra Leona'),
('Singapur', 'Estado_Singapur', 'Ciudad_Singapur', 'Dirección_Singapur'),
('Siria', 'Estado_Siria', 'Ciudad_Siria', 'Dirección_Siria'),
('Somalia', 'Estado_Somalia', 'Ciudad_Somalia', 'Dirección_Somalia'),
('Sri Lanka', 'Estado_Sri Lanka', 'Ciudad_Sri Lanka', 'Dirección_Sri Lanka'),
('Suazilandia', 'Estado_Suazilandia', 'Ciudad_Suazilandia', 'Dirección_Suazilandia'),
('Sudáfrica', 'Estado_Sudáfrica', 'Ciudad_Sudáfrica', 'Dirección_Sudáfrica'),
('Sudán', 'Estado_Sudán', 'Ciudad_Sudán', 'Dirección_Sudán'),
('Sudán del Sur', 'Estado_Sudán del Sur', 'Ciudad_Sudán del Sur', 'Dirección_Sudán del Sur'),
('Suecia', 'Estado_Suecia', 'Ciudad_Suecia', 'Dirección_Suecia'),
('Suiza', 'Estado_Suiza', 'Ciudad_Suiza', 'Dirección_Suiza'),
('Surinam', 'Estado_Surinam', 'Ciudad_Surinam', 'Dirección_Surinam'),
('Tailandia', 'Estado_Tailandia', 'Ciudad_Tailandia', 'Dirección_Tailandia'),
('Taiwán', 'Estado_Taiwán', 'Ciudad_Taiwán', 'Dirección_Taiwán'),
('Tanzania', 'Estado_Tanzania', 'Ciudad_Tanzania', 'Dirección_Tanzania'),
('Tayikistán', 'Estado_Tayikistán', 'Ciudad_Tayikistán', 'Dirección_Tayikistán'),
('Timor Oriental', 'Estado_Timor Oriental', 'Ciudad_Timor Oriental', 'Dirección_Timor Oriental'),
('Togo', 'Estado_Togo', 'Ciudad_Togo', 'Dirección_Togo'),
('Tonga', 'Estado_Tonga', 'Ciudad_Tonga', 'Dirección_Tonga'),
('Trinidad y Tobago', 'Estado_Trinidad y Tobago', 'Ciudad_Trinidad y Tobago', 'Dirección_Trinidad y Tobago'),
('Túnez', 'Estado_Túnez', 'Ciudad_Túnez', 'Dirección_Túnez'),
('Turkmenistán', 'Estado_Turkmenistán', 'Ciudad_Turkmenistán', 'Dirección_Turkmenistán'),
('Turquía', 'Estado_Turquía', 'Ciudad_Turquía', 'Dirección_Turquía'),
('Tuvalu', 'Estado_Tuvalu', 'Ciudad_Tuvalu', 'Dirección_Tuvalu'),
('Ucrania', 'Estado_Ucrania', 'Ciudad_Ucrania', 'Dirección_Ucrania'),
('Uganda', 'Estado_Uganda', 'Ciudad_Uganda', 'Dirección_Uganda'),
('Uruguay', 'Estado_Uruguay', 'Ciudad_Uruguay', 'Dirección_Uruguay'),
('Uzbekistán', 'Estado_Uzbekistán', 'Ciudad_Uzbekistán', 'Dirección_Uzbekistán'),
('Vanuatu', 'Estado_Vanuatu', 'Ciudad_Vanuatu', 'Dirección_Vanuatu'),
('Vaticano', 'Estado_Vaticano', 'Ciudad_Vaticano', 'Dirección_Vaticano'),
('Venezuela', 'Estado_Venezuela', 'Ciudad_Venezuela', 'Dirección_Venezuela'),
('Vietnam', 'Estado_Vietnam', 'Ciudad_Vietnam', 'Dirección_Vietnam'),
('Yemen', 'Estado_Yemen', 'Ciudad_Yemen', 'Dirección_Yemen'),
('Yibuti', 'Estado_Yibuti', 'Ciudad_Yibuti', 'Dirección_Yibuti'),
('Zambia', 'Estado_Zambia', 'Ciudad_Zambia', 'Dirección_Zambia'),
('Zimbabue', 'Estado_Zimbabue', 'Ciudad_Zimbabue', 'Dirección_Zimbabue');